### ISSUE TITLE
Feature: Need a way to change the title of the round

### ISSUE THREAD

**Issue by ElijahPrince73** [g-loot/react-tournament-brackets#25]
Right now the last 2 rounds say semi-final and final I would like the ability to change them to Finals and Grand Finals

**Comment by prodrive11** [comment]
Same, i'd like to use it to show shards for huge tournaments (tennis), so final round would become  ie. `top 32`
Also mirror tree to grow to the right would be great.  

@ElijahPrince73 did you find a workaround?

**Comment by Shenato** [comment]
This should be fixed now let me know if not and I can re-open this ticket 👍
